Repository java-is-coffee/Front-PolaRoad, pull requests merged in 2024-04, with the labels that each got.

#24 Feat/PO-45 메인 페이지
  package-lock.json
  src/components/Home/HomeComponent.module.css
  src/components/Home/HomeModal.module.css
  src/components/Home/HomeModal.tsx
  src/components/Home/HomePosting.module.css
  src/components/Home/HomePosting.tsx
Labels: 🛠️ Feature

#25 Feat : PO-75 포스트 상세 보기 페이지 구현
  src/api/comments/getPostComments.ts
  src/api/comments/postNewComment.ts
  src/api/follow/postFollowMember.ts
  src/api/member/getMemberInfo.ts
  src/api/post/patchPostGoodToggle.ts
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.module.css
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.tsx
  src/components/comments/SingleComment.tsx
  src/components/header/cardLIst/CardLIstHeader.tsx
  src/components/header/cardLIst/CardListHeader.module.css
  src/components/map/PostMap.module.css
  src/components/map/PostMap.tsx
  src/components/modal/newPost/NewPostModal.tsx
  src/components/modal/option/PostOptionModal.module.css
  src/components/modal/option/PostOptionModal.tsx
  src/containers/post/PostDetails.module.css
  src/containers/post/PostDetails.tsx
  src/containers/post/comments/PostComments.module.css
  src/containers/post/comments/PostComments.tsx
  src/containers/post/postCardList/web/PostCardList.module.css
  src/containers/post/postCardList/web/PostCardList.tsx
  src/enum/modalOptionTypes.ts
  src/hooks/map/useKakaoMap.ts
  src/hooks/modal/newFile/useIndexChange.ts
  src/hooks/modal/newFile/useSingleCard.ts
  src/interface/comments/ICommentsDTO.ts
  src/interface/map/IRoutesPointType.ts
  src/interface/member/IMemberInfoDetails.ts
  src/interface/post/IPostDTO.ts
Labels: 🛠️ Feature

#26 Feat : PO-5 useSearchParam을 통한 필터 & 검색 기능 저장 & 모바일 화면 기초 구현
  src/api/explore/getPostList.ts
  src/api/login/postLogin.ts
  src/api/token/axiosInstance.ts
  src/api/token/getAccessToken.ts
  src/components/bottom/BottomNavigator.tsx
  src/components/button/explore/ScrollButton.tsx
  src/components/button/explore/ScrollButtonLeft.tsx
  src/components/button/explore/ScrollButtonRight.tsx
  src/components/card/mainPhoto/MainPhotoCard.module.css
  src/components/card/mainPhoto/MainPhotoCard.tsx
  src/components/category/MainCategory.module.css
  src/components/category/MainCategory.tsx
  src/components/dropDown/search/SearchDropdown.tsx
  src/components/form/explore/mobile/MobileSearchForm.module.css
  src/components/form/explore/mobile/MobileSearchForm.tsx
  src/components/form/header/HeaderSearch.tsx
  src/components/grid/explorePhotoList/ExplorePhotoList.module.css
  src/components/grid/explorePhotoList/ExplorePhotoList.tsx
  src/components/header/Header.tsx
  src/components/header/mobile/MobileHeader.module.css
  src/components/header/mobile/MobileHeader.tsx
  src/components/header/web/WebHeader.module.css
  src/components/header/web/WebHeader.tsx
  src/containers/explore/ExploreContainer.module.css
  src/containers/explore/ExploreContainer.tsx
  src/enum/ConceptOptionType.ts
  src/hooks/explore/useCustomParam.ts
  src/hooks/storeValue/useStoreValue.ts
  src/interface/explore/ExplorePost.ts
  src/redux/reducers/explore/explorePostReducer.ts
  src/redux/reducers/explore/filterReducer.ts
  src/redux/reducers/explore/setCategoryReducer.ts
  src/redux/store/store.ts
  src/routes/Explore.tsx
  src/routes/Home.tsx
  src/routes/MyPage.tsx
  src/routes/Post.tsx
Labels: 🛠️ Feature

#31 Feat : PO - 5 모바일 컨셉트 필터 기능 추가 & 메인 헤더에 유저 이미지 출력 & 모바일 최근 검색어 목록 출력 & 리덕스 제거 및 쿼리 적용
  package-lock.json
  src/App.tsx
  src/components/category/MainCategory.module.css
  src/components/category/MainCategory.tsx
  src/components/dropDown/search/SearchDropdown.module.css
  src/components/dropDown/search/SearchDropdown.tsx
  src/components/form/explore/mobile/MobileSearchForm.module.css
  src/components/form/explore/mobile/MobileSearchForm.tsx
  src/components/form/explore/mobile/MobileSearchHistory.module.css
  src/components/form/explore/mobile/MobileSearchHistory.tsx
  src/components/form/header/HeaderSearch.tsx
  src/components/grid/explorePhotoList/ExplorePhotoList.tsx
  src/components/header/mobile/MobileHeader.module.css
  src/components/header/mobile/MobileHeader.tsx
  src/components/header/web/WebHeader.tsx
  src/containers/explore/ExploreContainer.module.css
  src/containers/explore/ExploreContainer.tsx
  src/hooks/storeValue/useStoreValue.ts
  src/index.tsx
  src/redux/reducers/explore/exploreMobileSetting.ts
  src/redux/reducers/explore/explorePostReducer.ts
  src/redux/store/store.ts
Labels: 🛠️ Feature

#32 Feat : PO-85 새앨범 & 위시리스트 모달
  src/App.tsx
  src/api/card/getCardList.ts
  src/api/wishlist/getWishList.ts
  src/api/wishlist/postNewWishList.ts
  src/components/button/user/UserActionBtn.module.css
  src/components/card/newAlbum/NewAlbumCard.module.css
  src/components/card/newAlbum/NewAlbumCard.tsx
  src/components/form/album/NewAlbumTextForm.tsx
  src/components/form/album/SelectAlbumCardForm.module.css
  src/components/form/album/SelectAlbumCardForm.tsx
  src/components/input/UniversalInput.module.css
  src/components/input/UniversalInput.tsx
  src/components/modal/album/newAlbum/NewAlbumModal.module.css
  src/components/modal/album/newAlbum/NewAlbumModal.tsx
  src/components/modal/newPost/NewPostModal.tsx
  src/components/modal/warn/WarningModal.module.css
  src/components/modal/warn/WarningModal.tsx
  src/components/modal/wish/newWishList/NewWishListModal.module.css
  src/components/modal/wish/newWishList/NewWishListModal.tsx
  src/containers/profile/ProfileCard.tsx
  src/enum/modalOptionTypes.ts
  src/index.tsx
  src/interface/card/ICardListDTO.ts
  src/interface/wish/IWishList.ts
  src/routes/Explore.tsx
  src/routes/Home.tsx
  src/routes/MyPage.tsx
Labels: 🛠️ Feature

#35 Fix : PO-88 포스트 생성 모달 오류 수정
  src/api/post/postNewPost.ts
  src/components/form/card/CardForm.tsx
  src/components/form/card/NewCardList.tsx
  src/interface/card/INewCard.ts
Labels: 🐛Hotfix

#38 Fix : PO-83 지도 불러오기 오류 수정
  src/components/map/PostMap.module.css
  src/components/map/PostMap.tsx
  src/hooks/error/useErrorHandler.ts
  src/hooks/map/useKakaoMap.ts
Labels: 🐛Hotfix

#42 Feat : PO-18 지도 페이지 기본 구현
  package-lock.json
  package.json
  public/basic/marker.png
  src/App.tsx
  src/api/mapPost/getCardsByMapArea.ts
  src/components/card/map/MapCard.module.css
  src/components/card/map/MapCard.tsx
  src/components/header/web/WebHeader.module.css
  src/components/header/web/WebHeader.tsx
  src/components/map/PostMap.tsx
  src/components/map/mapHeader/MapHeader.module.css
  src/components/map/mapHeader/MapHeader.tsx
  src/containers/map/MapPageContainer.module.css
  src/containers/map/MapPageContainer.tsx
  src/containers/map/sideContainer/MapSideConatainer.tsx
  src/containers/map/sideContainer/MapSideContainer.module.css
  src/containers/myPage/MyPageContainer.tsx
  src/hooks/map/useKakaoMap.ts
  src/interface/explore/ExplorePost.ts
  src/interface/explore/IPostListDTO.ts
  src/interface/map/IMapCard.ts
  src/routes/MapPage.tsx
  src/routes/MyPage.tsx
Labels: 🛠️ Feature

#46 Styles : PO-96 댓글 스타일 수정
  src/components/button/user/UserOptionBtn.module.css
  src/components/comments/SingleComment.module.css
  src/components/comments/SingleComment.tsx
  src/components/header/userGallery/UserGalleryHeader.module.css
  src/components/modal/post/PostPreviewModal.module.css
  src/containers/post/comments/PostComments.module.css
  src/containers/post/comments/PostComments.tsx
  src/containers/profile/ProfileCard.tsx
  src/interface/comments/ICommentsDTO.ts
Labels: 🎨Styles

#51 Feat & Fix : 마이페이지 및 포스트 수정
  src/api/explore/getFollwerPostList.ts
  src/api/post/deletePost.ts
  src/components/card/mainPhoto/MainPhotoCard.module.css
  src/components/card/postDetail/SingleCardDetails.module.css
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.module.css
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.tsx
  src/components/category/MainCategory.module.css
  src/components/category/MainCategory.tsx
  src/components/form/card/CardForm.module.css
  src/components/form/card/CardForm.tsx
  src/components/form/card/NewCardList.tsx
  src/components/form/header/SearchModal.tsx
  src/components/form/post/NewPostDetails.module.css
  src/components/form/post/NewPostDetails.tsx
  src/components/grid/explorePhotoList/ExplorePhotoList.tsx
  src/components/grid/userPhotoGallery/wishLIstGrid/WishListGrid.tsx
  src/components/header/web/WebHeader.tsx
  src/components/modal/newPost/NewPostModal.module.css
  src/components/modal/newPost/NewPostModal.tsx
  src/components/modal/option/PostOptionModal.module.css
  src/components/modal/option/PostOptionModal.tsx
  src/components/modal/warn/deleteWarning/DeleteWarningModal.tsx
  src/components/modal/wish/newWishList/NewWishListModal.tsx
  src/components/paging/card/CardPaging.module.css
  src/components/paging/card/CardPaging.tsx
  src/containers/post/PostDetails.module.css
  src/containers/post/postCardList/mobile/CarouselPostCardsList.tsx
  src/containers/post/postCardList/web/PostCardLIstCarousel.tsx
  src/containers/post/postCardList/web/PostCardList.tsx
  src/interface/explore/ExplorePost.ts
  src/redux/reducers/wishList/wishListReducers.ts
  src/redux/store/store.ts
  src/routes/MyPage.tsx
  src/routes/Post.tsx
Labels: 🐛Hotfix, 🛠️ Feature

#52 Feat : PO-98 다른 유저 프로필 보기 기능 추가
  src/api/follow/postFollowMember.ts
  src/api/member/getOtherMemberInfo.ts
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.module.css
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.tsx
  src/components/form/card/CardForm.tsx
  src/components/form/post/NewPostDetails.module.css
  src/components/form/post/NewPostDetails.tsx
  src/components/grid/userPhotoGallery/wishListPost/WishListPostGrid.tsx
  src/components/header/cardLIst/CardLIstHeader.tsx
  src/components/header/cardLIst/CardListHeader.module.css
  src/components/modal/member/miniProfile/MiniProfileModal.module.css
  src/components/modal/member/miniProfile/MiniProfileModal.tsx
  src/components/modal/option/PostOptionModal.tsx
  src/components/paging/card/CardPaging.module.css
  src/components/paging/card/CardPaging.tsx
  src/containers/miniProfile/MiniProfile.module.css
  src/containers/miniProfile/MiniProfile.tsx
  src/containers/myPage/MyPageContainer.module.css
  src/containers/myPage/MyPageContainer.tsx
  src/containers/post/postCardList/mobile/CarouselPostCardsList.tsx
  src/containers/post/postCardList/web/PostCardLIstCarousel.tsx
  src/containers/post/postCardList/web/PostCardList.tsx
  src/containers/profile/ProfileCard.module.css
  src/enum/modalOptionTypes.ts
  src/interface/member/IOtherMemberInfo.ts
  src/interface/post/IPostDTO.ts
  src/routes/MyPage.tsx
  src/routes/Post.tsx
  src/utils/card/validateCardDetails.ts
Labels: 🛠️ Feature

#56 Feat : PO-5 포스트 모달 & 탐색 페이지 & 팔로우 언팔로우 기능 & 댓글 삭제 기능 구현
  src/api/comments/deleteComment.ts
  src/api/explore/getFollwerPostList.ts
  src/api/explore/getPostList.ts
  src/api/follow/getIsFollowMember.ts
  src/api/follow/postFollowMember.ts
  src/api/token/axiosInstance.ts
  src/components/card/mainPhoto/MainPhotoCard.module.css
  src/components/card/mainPhoto/MainPhotoCard.tsx
  src/components/category/MainCategory.tsx
  src/components/comments/SingleComment.module.css
  src/components/comments/SingleComment.tsx
  src/components/form/card/CardForm.module.css
  src/components/form/card/CardForm.tsx
  src/components/form/explore/web/WebSearchHistory.tsx
  src/components/form/header/SearchModal.tsx
  src/components/grid/cardListGrid/CardGrid.tsx
  src/components/grid/explorePhotoList/ExplorePhotoList.module.css
  src/components/grid/explorePhotoList/ExplorePhotoList.tsx
  src/components/header/web/WebHeader.tsx
  src/components/login/LoginComponent.tsx
  src/components/login/RegisterComponent.tsx
  src/components/modal/comment/CommentEditModal.module.css
  src/components/modal/comment/CommentEditModal.tsx
  src/components/modal/comment/CommentOptionModal.module.css
  src/components/modal/comment/CommentOptionModal.tsx
  src/components/modal/member/miniProfile/MiniProfileModal.tsx
  src/components/modal/newPost/NewPostModal.module.css
  src/components/modal/post/PostPreviewModal.tsx
  src/containers/miniProfile/MiniProfile.tsx
  src/containers/post/PostDetails.tsx
  src/containers/post/comments/PostComments.tsx
  src/enum/modalOptionTypes.ts
  src/hooks/explore/useExploreHooks.ts
  src/hooks/login/useLogin.ts
  src/routes/Post.tsx
Labels: 🛠️ Feature

#59 Feat : PO-13 회원가입 이메일 인증 구현 배포
  src/api/login/postRegister.ts
  src/api/login/postSendEmail.ts
  src/components/login/RegisterComponent.tsx
  src/hooks/login/useRegister.ts
Labels: 🛠️ Feature

#60 Feat & Styles : PO-97 스타일적인 문제 해결 & 지도 검색 기능 추가 & 지도 마커에 이미지 추가
  public/index.html
  src/App.tsx
  src/components/Home/HomeFooter.tsx
  src/components/bottom/BottomNavigator.tsx
  src/components/button/user/UserActionBtn.module.css
  src/components/button/user/UserOptionBtn.module.css
  src/components/card/postDetail/SingleCardDetails.tsx
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.tsx
  src/components/header/mobile/MobileHeader.module.css
  src/components/modal/post/PostPreviewModal.module.css
  src/containers/explore/ExploreContainer.module.css
  src/containers/map/MapPageContainer.tsx
  src/containers/map/moblie/MapPageContainerMoblie.tsx
  src/containers/map/moblie/sideConatainer/MapSideContainerMobile.module.css
  src/containers/map/moblie/sideConatainer/MapSideContainerMobile.tsx
  src/containers/map/sideContainer/MapSideContainer.module.css
  src/containers/post/PostDetails.module.css
  src/containers/post/mobile/PostDetailsMobile.module.css
  src/containers/post/mobile/PostDetailsMoblie.tsx
  src/containers/post/postCardList/web/PostCardLIstCarousel.tsx
  src/containers/post/postCardList/web/PostCardList.module.css
  src/hooks/bucket/useBucket.ts
  src/hooks/map/useKakaoMap.ts
  src/routes/Home.tsx
  src/service-worker.ts
Labels: 🛠️ Feature

#61 PO-97 스타일적인 문제 해결 & 지도 검색 기능 추가 & 지도 마커에 이미지 추가 배포
  public/index.html
  src/App.tsx
  src/components/Home/HomeFooter.tsx
  src/components/bottom/BottomNavigator.tsx
  src/components/button/user/UserActionBtn.module.css
  src/components/button/user/UserOptionBtn.module.css
  src/components/card/postDetail/SingleCardDetails.tsx
  src/components/card/postDetail/thumbnailCard/ThumbnailCard.tsx
  src/components/header/mobile/MobileHeader.module.css
  src/components/modal/post/PostPreviewModal.module.css
  src/containers/explore/ExploreContainer.module.css
  src/containers/map/MapPageContainer.tsx
  src/containers/map/moblie/MapPageContainerMoblie.tsx
  src/containers/map/moblie/sideConatainer/MapSideContainerMobile.module.css
  src/containers/map/moblie/sideConatainer/MapSideContainerMobile.tsx
  src/containers/map/sideContainer/MapSideContainer.module.css
  src/containers/post/PostDetails.module.css
  src/containers/post/mobile/PostDetailsMobile.module.css
  src/containers/post/mobile/PostDetailsMoblie.tsx
  src/containers/post/postCardList/web/PostCardLIstCarousel.tsx
  src/containers/post/postCardList/web/PostCardList.module.css
  src/hooks/bucket/useBucket.ts
  src/hooks/map/useKakaoMap.ts
  src/routes/Home.tsx
  src/service-worker.ts
Labels: :checkered_flag: Deploy

#64 Styles : PO-97 포스트 댓글 작성 스타일 수정 배포
  src/containers/map/moblie/sideConatainer/MapSideContainerMobile.module.css
  src/containers/map/moblie/sideConatainer/MapSideContainerMobile.tsx
  src/containers/post/comments/PostComments.module.css
  src/containers/post/postCardList/web/PostCardLIstCarousel.tsx
Labels: 🐛Hotfix, :checkered_flag: Deploy

#65 Fix : PO-97 keyword 오타 수정
  src/api/mapPost/getCardsByMapArea.ts
Labels: 🎨Styles, :checkered_flag: Deploy

#67 Chore : PO-97 로그 추가
  src/components/modal/album/newAlbum/NewAlbumModal.tsx
Labels: 🐛Hotfix

#68 Fix : PO-97 웹워커 설정 수정
  src/index.tsx
  src/serviceWorkerRegistration.ts
Labels: 🐛Hotfix

#69 Fix : PO-97 get 캐싱 삭제
  src/service-worker.ts
Labels: 🐛Hotfix, :checkered_flag: Deploy

#72 Fix : PO-97 위시리스트 불러오기 로직 수정
  src/components/grid/userPhotoGallery/wishListPost/WishListPostGrid.tsx
Labels: 🐛Hotfix, :checkered_flag: Deploy

#73 Fix : PO-97 위시리스트 불러오기 로직 수정
  src/components/grid/userPhotoGallery/wishListPost/WishListPostGrid.tsx
Labels: 🐛Hotfix

#74 Fix : PO-97 위시리스트 중복 추가 로직 수정
  src/components/grid/userPhotoGallery/wishListPost/WishListPostGrid.tsx
Labels: 🐛Hotfix, :checkered_flag: Deploy
